language: node_js
node_js: stable
cache:
  apt: true
  yarn: true
  npm: true
  directories:
  - node_modules
branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K ${encrypted_6148c8409cc2_key} -iv ${encrypted_6148c8409cc2_iv}
  -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/travis_rsa
- cp .travis/config ~/.ssh/config
- git config --global user.name 'Nightbone'
- git config --global user.email 'alvis.lui@gmail.com'
install:
- npm install hexo-cli -g
- npm install hexo-math --save
- npm install hexo-generator-searchdb --save
- npm install hexo-symbols-count-time --save
- npm install hexo-generator-feed --save
- npm install hexo-wordcount --save
- npm install mermaid --save
- npm install hexo-tag-mermaid --save
- npm install hexo-tag-plantuml --save
before_script:
- cd ./themes/next
- git clone https://github.com/theme-next/theme-next-fancybox3 source/lib/fancybox
- git clone https://github.com/theme-next/theme-next-jquery-lazyload source/lib/jquery_lazyload
- git clone https://github.com/theme-next/theme-next-needmoreshare2 source/lib/needsharebutton
- git clone https://github.com/theme-next/theme-next-pace source/lib/pace
- git clone https://github.com/theme-next/theme-next-pangu.git source/lib/pangu
- git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress
- cd ..
- cd ..
script:
- hexo -version
- hexo clean && hexo g
after_script:
- set -ev
- export TZ='Asia/Shanghai'
- cd ./public
- git config user.name "Nightbone"
- git config user.email "alvis.lui@gmail.com"
- git init
- git add .
- git commit -m "Site updated:`date +"%Y-%m-%d %H:%M:%S"`"
- git remote add origin git@github.com:Nightbone/Nightbone.github.io.git
- git push -u origin master -f
dd:
- openssl aes-256-cbc -K $encrypted_6148c8409cc2_key -iv $encrypted_6148c8409cc2_iv
  -in travis_rsa.enc -out travis_rsa -d
